# Generated by Django 6.0.7 on 2026-07-10 07:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, default='', verbose_name='公司简介')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='公司地址')),
                ('progress_stages', models.CharField(default='开始,进行中,结束', help_text='以英文逗号分隔的阶段名称，例如: 开始,水电,泥瓦,木工,验收', max_length=500, verbose_name='项目阶段')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '装修公司',
                'verbose_name_plural': '装修公司',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='案例标题')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='case_covers/', verbose_name='封面图')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='图片集')),
                ('video_url', models.URLField(blank=True, default='', verbose_name='视频链接')),
                ('description', models.TextField(blank=True, default='', verbose_name='案例描述')),
                ('style', models.CharField(blank=True, default='', max_length=100, verbose_name='装修风格')),
                ('area', models.CharField(blank=True, default='', help_text='例如: 120㎡', max_length=50, verbose_name='面积')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预算（万元）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='app.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '装修案例',
                'verbose_name_plural': '装修案例',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', '公司管理员'), ('employee', '员工')], default='employee', max_length=20, verbose_name='角色')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(blank=True, help_text='超级管理员可以不绑定公司', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='app.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['company', 'username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='客户电话')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='项目地址')),
                ('current_stage', models.IntegerField(default=0, help_text='对应公司项目阶段列表中的序号，从 0 开始', verbose_name='当前阶段序号')),
                ('stage_name_snapshot', models.CharField(blank=True, default='', help_text='创建/更新时自动保存的阶段名称', max_length=100, verbose_name='阶段名称快照')),
                ('content', models.TextField(blank=True, default='', verbose_name='进度描述')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='现场图片')),
                ('video_url', models.URLField(blank=True, default='', verbose_name='视频链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='app.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '项目进度',
                'verbose_name_plural': '项目进度',
                'ordering': ['-created_at'],
            },
        ),
    ]
