# Generated by Django 6.0.7 on 2026-08-07 11:34

import app.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="公司名称")),
                (
                    "credit_code",
                    models.CharField(
                        help_text="仅系统管理员可编辑",
                        max_length=18,
                        verbose_name="社会统一信用代码",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=app.models.company_logo_path,
                        verbose_name="Logo",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="公司简介"),
                ),
                (
                    "phone",
                    models.CharField(
                        default="", max_length=30, verbose_name="联系电话"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default="", max_length=300, verbose_name="公司地址"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("inactive", "停用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "max_video_size",
                    models.IntegerField(
                        choices=[(200, "200MB"), (500, "500MB")],
                        default=200,
                        help_text="影响案例和项目进度的视频上传上限",
                        verbose_name="视频大小限制（MB）",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "established_date",
                    models.DateField(
                        blank=True,
                        help_text="公司成立日期",
                        null=True,
                        verbose_name="成立日期",
                    ),
                ),
            ],
            options={
                "verbose_name": "公司",
                "verbose_name_plural": "公司",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "phone",
                    models.CharField(max_length=30, unique=True, verbose_name="电话"),
                ),
                (
                    "address",
                    models.CharField(default="", max_length=300, verbose_name="住址"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "客户",
                "verbose_name_plural": "客户",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SmsCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="手机号"
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="验证码")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("customer_login", "客户登录"),
                            ("staff_login", "员工登录"),
                        ],
                        default="customer_login",
                        max_length=20,
                        verbose_name="用途",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                ("used", models.BooleanField(default=False, verbose_name="已使用")),
            ],
            options={
                "verbose_name": "短信验证码",
                "verbose_name_plural": "短信验证码",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="案例标题")),
                (
                    "cover",
                    models.ImageField(
                        null=True,
                        upload_to=app.models.case_media_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "webp",
                                    "bmp",
                                    "tiff",
                                    "svg",
                                ],
                                message="封面图仅支持图片格式（jpg/jpeg/png/gif/webp/bmp/tiff/svg）",
                            )
                        ],
                        verbose_name="封面图",
                    ),
                ),
                (
                    "images",
                    models.JSONField(blank=True, default=list, verbose_name="图片集"),
                ),
                (
                    "video",
                    models.FileField(
                        null=True,
                        upload_to=app.models.case_media_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "mp4",
                                    "mov",
                                    "avi",
                                    "mkv",
                                    "wmv",
                                    "flv",
                                    "webm",
                                    "m4v",
                                ],
                                message="仅支持视频文件（mp4/mov/avi/mkv/wmv/flv/webm/m4v）",
                            )
                        ],
                        verbose_name="视频文件",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="案例描述"),
                ),
                (
                    "style",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="风格"
                    ),
                ),
                (
                    "area",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="面积（㎡）"
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="预算（万元）",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("inactive", "停用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="app.company",
                        verbose_name="所属公司",
                    ),
                ),
            ],
            options={
                "verbose_name": "案例",
                "verbose_name_plural": "案例",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=64, unique=True, verbose_name="令牌"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="签发时间"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="app.customer",
                        verbose_name="客户",
                    ),
                ),
            ],
            options={
                "verbose_name": "客户令牌",
                "verbose_name_plural": "客户令牌",
            },
        ),
        migrations.CreateModel(
            name="ProjectProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(max_length=200, verbose_name="项目名称"),
                ),
                ("address", models.CharField(max_length=300, verbose_name="项目地址")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("inactive", "停用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="app.company",
                        verbose_name="所属公司",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="客户信息由客户表提供",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="app.customer",
                        verbose_name="客户",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目进度",
                "verbose_name_plural": "项目进度",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="阶段名称"
                    ),
                ),
                (
                    "image_0",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=app.models.stage_image_path(0),
                        verbose_name="图片1",
                    ),
                ),
                (
                    "image_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=app.models.stage_image_path(1),
                        verbose_name="图片2",
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=app.models.stage_image_path(2),
                        verbose_name="图片3",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="阶段描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="app.projectprogress",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目阶段",
                "verbose_name_plural": "项目阶段",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="姓名")),
                (
                    "phone",
                    models.CharField(
                        help_text="用于短信验证码登录",
                        max_length=30,
                        unique=True,
                        verbose_name="联系电话",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="电子邮件地址"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("项目负责人", "公司管理员")],
                        default="项目负责人",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次登录时间"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff",
                        to="app.company",
                        verbose_name="所属公司",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工",
                "verbose_name_plural": "员工",
                "db_table": "app_staff",
                "ordering": ["company", "name"],
            },
        ),
        migrations.AddField(
            model_name="projectprogress",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="app.staff",
                verbose_name="负责人",
            ),
        ),
    ]
