# Generated by Django 6.0.7 on 2026-07-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('root', '超级管理员'), ('admin', '公司管理员'), ('employee', '员工')], default='employee', max_length=20, verbose_name='角色'),
        ),
    ]
