# Generated by Django 6.0.7 on 2026-07-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '公司管理员')], default='admin', max_length=20, verbose_name='角色'),
        ),
    ]
