# Generated by Django 6.0.7 on 2026-07-12 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='video_file',
            field=models.FileField(blank=True, help_text='上传视频文件，支持 MP4、WebM 等格式', null=True, upload_to='case_videos/', verbose_name='视频文件'),
        ),
        migrations.AddField(
            model_name='company',
            name='max_images_tier',
            field=models.CharField(choices=[('basic', '基础版（最多4张）'), ('premium', '高级版（最多8张）')], default='basic', help_text='影响案例和项目进度的图片上传上限', max_length=20, verbose_name='案例图片数量档次'),
        ),
        migrations.AddField(
            model_name='company',
            name='max_video_size_tier',
            field=models.CharField(choices=[('basic', '基础版（最大50MB）'), ('premium', '高级版（最大200MB）')], default='basic', help_text='影响案例和项目进度的视频上传上限', max_length=20, verbose_name='视频大小档次'),
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='video_file',
            field=models.FileField(blank=True, help_text='上传视频文件，支持 MP4、WebM 等格式', null=True, upload_to='progress_videos/', verbose_name='视频文件'),
        ),
        migrations.CreateModel(
            name='CaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='case_images/', verbose_name='参考图')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_images', to='app.case', verbose_name='所属案例')),
            ],
            options={
                'verbose_name': '参考图',
                'verbose_name_plural': '参考图',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectProgressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='progress_images/', verbose_name='现场图片')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_images', to='app.projectprogress', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '现场图片',
                'verbose_name_plural': '现场图片',
                'ordering': ['sort_order'],
            },
        ),
    ]
