# Generated by Django 6.0.7 on 2026-07-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_case_video_file_company_max_images_tier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='company',
            name='max_images_tier',
        ),
        migrations.RemoveField(
            model_name='company',
            name='max_video_size_tier',
        ),
        migrations.AddField(
            model_name='company',
            name='max_video_size',
            field=models.IntegerField(choices=[(200, '200MB'), (500, '500MB')], default=200, help_text='影响案例和项目进度的视频上传上限', verbose_name='视频大小限制（MB）'),
        ),
        migrations.DeleteModel(
            name='CaseImage',
        ),
    ]
