# Generated by Django 6.0.7 on 2026-07-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_case_video_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectprogress',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='projectprogress',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='images',
            field=models.JSONField(blank=True, default=dict, verbose_name='阶段图片'),
        ),
        migrations.DeleteModel(
            name='ProjectProgressImage',
        ),
    ]
