# Generated by Django 6.0.7 on 2026-07-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_projectprogress_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprogress',
            name='project_name',
            field=models.CharField(default='', max_length=200, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='current_stage',
            field=models.IntegerField(default=0, help_text='对应公司项目阶段列表中的序号，从 0 开始', verbose_name='当前阶段'),
        ),
    ]
